GET http://localhost:8080/

###

GET http://localhost:8080/login
### 

POST http://localhost:8080/login
Content-type: application/json

{
    "email": "luizalber@gmail.com",
    "senha": "senhaliuzadx" 
}

### 

PUT http://localhost:8080/login?id=56c8c961-0e35-42b8-a8e5-32b2d1016fc8
Content-type: application/json

{
    "email": "pedroluiza@gmail.com",
    "senha": "123456"
}

###

POST http://localhost:8080/api/login/usuario
Content-Type: application/json

{
    "email": "turing@gmail.com",
    "senha": "senha"
}